services:
  app:
    build: .
    ports:
      - '6969:6969'
    depends_on:
      - db
    environment:
      DB_NAME: /run/secrets/DB_NAME
      MONGO_USER: /run/secrets/MONGO_USER
      MONGO_PASS: /run/secrets/MONGO_PASS
      MONGO_URL_LOCAL: /run/secrets/MONGO_URL_LOCAL
      MONGO_URL: /run/secrets/MONGO_URL
      SERVER_PORT: 6969
      SHUTDOWN_INTERVAL: 1000
      AWS_ACCESS_ID: /run/secrets/AWS_ACCESS_ID
      AWS_ACCESS_SECRET_KEY: /run/secrets/AWS_ACCESS_SECRET_KEY

  db:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  # mongo-admin:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ADMIN_USERNAME: kadali
  #     ADMIN_PASSWORD: 12345
  #     MONGO_SERVER: mongodb
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
